// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package repository

type User struct {
	ID    int64   `db:"id" json:"id"`
	Name  string  `db:"name" json:"name"`
	Email string  `db:"email" json:"email"`
	Bio   *string `db:"bio" json:"bio"`
}
